### ISSUE TITLE
VSCodium Extension doesn't function properly

### ISSUE THREAD

**Issue by expp121** [mercedes-benz/sechub-plugin-vscode#22]
After opening a report in VsCodium using the SecHub extension.
![image](https://user-images.githubusercontent.com/29148934/195323494-51bd44c0-d45c-4fe1-b3b5-5d64f0b29b6b.png)
And trying to click on one of the findings, to see where the vulnerability is located, does nothing!
Looking in the extension logs, there were some ```uncaught errors``` from the extension.
![image](https://user-images.githubusercontent.com/29148934/195326110-55cd2db6-2e75-48ad-9f4c-ce3de1c47611.png)

Reading the logs show this output:
```
[2022-10-10 12:00:00.021] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'length')
	at openInEditor (/home/user/.vscode-oss/extensions/mercedes-benz.sechub-0.1.3/out/action/callHierarchyViewActions.js:32:98)
	at callBack (/home/user/.vscode-oss/extensions/mercedes-benz.sechub-0.1.3/out/action/callHierarchyViewActions.js:11:13)
	at n._executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:111324)
	at n._doExecuteCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:110142)
	at n.executeCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:110002)
	at Object.executeCommand (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:33656)
	at /home/user/.vscode-oss/extensions/mercedes-benz.sechub-0.1.3/out/action/reportViewActions.js:22:33
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5) sechubCallHierarchyView.selectNode {"value":"Mercedes-Benz.sechub","_lower":"mercedes-benz.sechub"}
```
And the used report was:
```
{
   "result": {
      "count": 2,
      "findings": [
         {
            "id": 1,
            "description": "Subprocess launched with variable",
            "name": "Subprocess launched with variable",
            "severity": "HIGH",
            "code": {
               "location": "##################",
               "line": 20,
               "column": 17,
               "source": "out, err := exec.Command(command).Output() // Weakness: OS command injection; CWE-78"
            },
            "type": "codeScan",
            "cweId": 78
         },
         {
            "id": 2,
            "description": "SQL string formatting",
            "name": "SQL string formatting",
            "severity": "HIGH",
            "code": {
               "location": "##################",
               "line": 16,
               "column": 10,
               "source": "q := fmt.Sprintf(\"SELECT * FROM foo where name = '%s'\", os.Args[1]) //Error: SQL Injection; CWE-89"
            },
            "type": "codeScan",
            "cweId": 89
         }
      ]
   },
   "status": "SUCCESS",
   "jobUUID": "########-####-####-####-############",
   "trafficLight": "RED",
   "reportVersion": "1.0",
   "messages": []
}

```
> __Note: Some information was intentionally replaced with '#'__

VSCodium Version: 1.72.0 (Not certain, might've updated after creating the issue)
> Release: 22279

SecHub Plugin Version: 0.1.3

**Comment by Jeeppler** [comment]
@expp121 thank you for reporting the issue.

**Comment by de-jcup** [comment]
@expp121 : Thank you for reporting the issue.

Could you please describe
- exact version of VSCode/VSCodium/Eclipse Theia you have used
- the SecHub plugin version you have used
- if you have tried the same report with the Eclipse or the IntelliJ plugin or with another VSCode/VSCodium/Eclipse Theia as well. If yes, did you have the same experience?

**Comment by Jeeppler** [comment]
The plugin works for me.

I tried it with:

~~~
Version: 1.72.2
Release: 22289
Commit: 378660f7dd07287aa34acf90e8fec157425c1ac8
Date: 2022-10-16T23:03:19.989Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-52-generic
Sandboxed: No
~~~

and plugin version: `v0.1.3`
